version: "3.7"

services:

  postgres:
    image: jloomisvce/val_species-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build:
      context: ./val_species-db
    ports:
      - '6543:5432'
    volumes:
      - val_species-db:/var/lib/postgresql/data

volumes:
  val_species-db:
