version: "3.7"

services:

  val_species-db-postgis:
    image: val_species-db-postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build:
      context: ./val_species-db
    ports:
      - '6543:5432'
    volumes:
      - val_species-db:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  val_species-api:
    image: jloomisvce/val_species-api:latest
    build:
      context: ./val_species-api
    environment:
      DB_SCHEMA: val_species
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      VIRTUAL_HOST: api.val_species.vtatlasoflife.org
    depends_on:
      - val_species-db-postgis
      - nginx-proxy
#    ports:
#      - '3000:3000'

volumes:
  val_species-db:
