version: "3.7"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  taxonomy:
    #image: jloomisvce/taxonomy:latest
    image: $DOCKER_USERNAME/taxonomy:latest
    command: "npm run migrate && npm run pm2"
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      VIRTUAL_HOST: taxonomy.vtatlasoflife.org
    depends_on:
      - postgres
      - nginx-proxy
    ports:
      - '3000:3000'
